### ISSUE TITLE
Linguagem utilizada para se comunicar com o usuário

### ISSUE THREAD

**Issue by jeehmilena** [carolina-queiroz/TesteFeedback#1]
Carol percebi que você usou o inglês para apresentar as mensagens para o usuário, nesse caso como nosso cliente é brasileiro as mensagens deveriam estar em português.

https://github.com/carolina-queiroz/TesteFeedback/blob/1694576c8f1bf8f4defa52a753ad6bb4cfc39244/Main.java#L5

**Comment by carolina-queiroz** [comment]
Minha linguagem é universal

**Comment by carolina-queiroz** [comment]
Finalizada
