### ISSUE TITLE
Alterar para variavel em portugês

### ISSUE THREAD

**Issue by jeehmilena** [carolina-queiroz/TesteFeedback#2]
Pra melhor legibilidade altere essa variavel para portugues

https://github.com/carolina-queiroz/TesteFeedback/blob/1694576c8f1bf8f4defa52a753ad6bb4cfc39244/Main.java#L14

**Comment by carolina-queiroz** [comment]
Problema resolvido

**Comment by carolina-queiroz** [comment]
FECHANDO
